#!/usr/bin/env ruby

require 'PostfixParser.rb'
require 'Stack.rb'

if ARGV.length == 1
  filename = ARGV[0]
else
  puts "Wrong number of arguments"
  puts "./runpostfix <filename>"
  exit(1)
end

if not File.exist? filename
  puts "File \"#{filename}\" do not exist"
  exit(1)
end

pps = PostfixParseFile(ARGV[0])
wmStack = Stack.new
returnValue = wmStack.eat(pps)
exit(returnValue[1])
